# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapsKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMapsKit
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Google-Maps-iOS-Utils'

end
