# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFirstMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFirstMap
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'
pod 'DTMHeatmap'
end
