# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMap' do
  # Comment the next line if you don't want to use dynamic frameworks

    use_frameworks!
    # source 'https://github.com/googlemaps/google-maps-ios-utils.git'
      target 'Heatmap' do
       pod 'Google-Maps-iOS-Utils'

  # Pods for GoogleMap
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'DTMHeatmap'
  pod 'Alamofire'
end
  
